server.port=8084
spring.application.name=staff-service

# --- Base de donnees PostgreSQL (via docker-compose) ---
spring.datasource.url=jdbc:postgresql://staff-db:5432/staff_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Eureka (annuaire sur PC1 : remplace PC1_IP par la vraie IP) ---
eureka.client.service-url.defaultZone=http://192.168.1.102:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- Swagger ---
springdoc.swagger-ui.path=/swagger-ui.html
