server.port=8084
spring.application.name=staff-service

# --- Base de donnees PostgreSQL (via docker-compose) ---
spring.datasource.url=jdbc:postgresql://staff-db:5432/staff_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Eureka (annuaire sur PC1 : remplace PC1_IP par la vraie IP) ---
eureka.client.service-url.defaultZone=http://192.168.1.102:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- Swagger ---
springdoc.swagger-ui.path=/swagger-ui.html
# --- Kafka (communication asynchrone) ---
spring.kafka.bootstrap-servers=192.168.1.155:9094
spring.kafka.consumer.group-id=my-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
